'use strict';

const { mergeModuleExports } = require('./export-merge.cjs');

module.exports = mergeModuleExports([
  ['state', require('./state.cjs')],
  ['events', require('./events.cjs')],
  ['stage-state', require('./stage-state.cjs')],
  ['config', require('./config.cjs')],
  ['quality-runner', require('./quality-runner.cjs')],
  ['package-manager', require('./package-manager.cjs')],
  ['command-catalog', require('./command-catalog.cjs')],
  ['agents', require('./agents.cjs')],
  ['rules', require('./rules.cjs')],
  ['init', require('./init.cjs')],
  ['prd-intake', require('./prd-intake.cjs')],
  ['gates', require('./gates.cjs')],
  ['guidance', require('./guidance.cjs')],
  ['roadmap', require('./roadmap.cjs')],
  ['port-gsd', require('./port-gsd.cjs')],
  ['hash', require('./hash.cjs')],
  ['decision-log', require('./decision-log.cjs')],
  ['baseline', require('./baseline.cjs')],
  ['policy', require('./policy.cjs')],
  ['session', require('./session.cjs')],
  ['workflow-helpers', require('./workflow-helpers.cjs')],
  ['intent-catalog', require('./intent-catalog.cjs')],
  ['workflow', require('./workflow.cjs')],
  ['reporting', require('./reporting.cjs')],
  ['lifecycle', require('./lifecycle.cjs')],
  ['workbench', require('./workbench.cjs')],
  ['adoption', require('./adoption.cjs')],
  ['command-contracts', require('./command-contracts.cjs')],
  ['validate', require('./validate.cjs')],
  ['presets', require('./presets.cjs')],
  ['migrate', require('./migrate.cjs')],
  ['audit', require('./audit.cjs')],
  ['fragments', require('./fragments.cjs')],
  ['health', require('./health.cjs')],
  ['repo-analysis', require('./repo-analysis.cjs')],
  ['planning', require('./planning.cjs')],
  ['artifact-analysis', require('./artifact-analysis.cjs')],
  ['security-check', require('./security-check.cjs')],
  ['interrogation', require('./interrogation.cjs')]
]);
